version: "3"

services:
  app:
    build:
      context: .
      args:
        RUBY_VERSION: 3.1.0
        NODE_VERSION: 18
    command: bin/docker/dev
    tty: true
    stdin_open: true
    ports:
      - '3000:3000'
    volumes:
      - .:/railsapp:cached
      - bundle:/bundle
    environment:
      REDIS_URL: redis://redis:6379
    depends_on:
      - redis

  redis:
    image: redis:5.0-alpine
    ports:
      - '16379:6379'
    volumes:
      - redis-data:/data

volumes:
  redis-data:
  bundle:
